using System;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AgoRapide.Core;
using System.Reflection;
using AgoRapide.API;

/// <summary>
/// Note: <see cref="AgoRapide.Database.PropertyKeyForeignKeyAggregate"/> also resides in this file for the time being (see below). 
/// </summary>
namespace AgoRapide.Database {

    /// <summary>
    /// Note <see cref="BaseInjector"/> assumes <see cref="CacheUse.All"/> for all entities involved and therefore always queries <see cref="InMemoryCache"/> directly.
    /// 
    /// TODO: Class should probably be renamed into ForeignKeyAggregatesInjecter if all other injectors are stored within <see cref="BaseSynchronizer"/>. 
    /// </summary>
    [Class(
        Description =
            "Responsible for injecting values that are only to be stored dynamically in RAM.\r\n" +
            "That is, values that are not to be stored in database, neither to be synchronized from external source.",
        LongDescription =
            nameof(BaseInjector) + " injects values that can automatically be deduced from standard AgoRapide information\r\n" +
            "(a typical example would be aggregations over foreign keys).\r\n" +
            "Inherited classes inject additional values based on their own C# logic")]
    public class BaseInjector {

        /// <summary>
        /// Note that will also set <see cref="PropertyKeyAttribute.HasLimitedRange"/> as appropriate. 
        /// 
        /// Uses <see cref="PropertyKeyForeignKeyAggregate"/> as generated by <see cref="GetForeignKeyAggregateKeys"/>
        /// </summary>
        /// <param name="type"></param>
        /// <param name="entities"></param>
        /// <param name="db"></param>
        [ClassMember(
            Description = "Calculates the actual aggregates based on keys returned by -" + nameof(GetForeignKeyAggregateKeys) + "-.",
            LongDescription = "Example: If we have Persons and Projects and every Project has a foreign key LeaderPersonId, then this method will aggregate Count_ProjectLeaderPersonid for every Person.")]
        public static void CalculateForeignKeyAggregates(Type type, List<BaseEntity> entities, BaseDatabase db) => type.GetChildProperties().Values.Select(key => key as PropertyKeyForeignKeyAggregate).Where(key => key != null).ForEach(key => {
            var hasLimitedRange = true; var valuesFound = new HashSet<long>();

            // Akkurat samme problem her med index!
            /// Build index in order to avoid O(n^2) situation.
            var toEntitiesIndex = new Dictionary<long, List<BaseEntity>>();
            InMemoryCache.EntityCache.Values.
                Where(e => key.SourceEntityType.IsAssignableFrom(e.GetType())). /// TODO: Index entities by type in entity cache, in order no to repeat queries like this:
                ForEach(e => { /// TODO: Consider implementing indices like this in <see cref="InMemoryCache"/>
                    if (e.Properties.TryGetValue(key.ForeignKeyProperty.Key.CoreP, out var p)) {
                        var foreignKeyValue = p.V<long>();
                        if (!toEntitiesIndex.TryGetValue(foreignKeyValue, out var list)) list = (toEntitiesIndex[foreignKeyValue] = new List<BaseEntity>());
                        list.Add(e);
                    }
                });

            entities.ForEach(e => {
                InvalidObjectTypeException.AssertAssignable(e, type);
                // TODO: Note potential repeated calculations of sourceEntities here. We could have used LINQ GroupBy, but would then have to
                // TODO: take into account that the ForeignKeyProperty may actually also vary, not only the SourceEntityType

                // Unuseable because O(n^2)
                // var sourceEntities = InMemoryCache.GetMatchingEntities(key.SourceEntityType, new QueryIdKeyOperatorValue(key.ForeignKeyProperty.Key, Operator.EQ, e.Id), db);

                // New variant with index created above
                var sourceEntities = toEntitiesIndex.TryGetValue(e.Id, out var temp) ? temp : new List<BaseEntity>();

                if (key.ForeignKeyProperty.Key.CoreP == key.SourceProperty.Key.CoreP) {
                    if (key.AggregationType != AggregationType.Count) throw new InvalidEnumException(key.AggregationType, "Because " + nameof(key.ForeignKeyProperty));

                    var av = (long)sourceEntities.Count;
                    e.AddProperty(key, av); // Note cast since long is the preferred type for aggregations. 

                    if (!valuesFound.Contains(av)) {
                        if (valuesFound.Count >= 20) { // Note how we allow up to 20 DIFFERENT values, instead of values up to 20. This means that a distribution like 1,2,3,4,5,125,238,1048 still counts as limited.
                            hasLimitedRange = false;
                        } else {
                            valuesFound.Add(av);
                        }
                    }
                } else {
                    throw new NotImplementedException(key.SourceProperty.Key.PToString);
                }
            });
            key.Key.A.HasLimitedRange = hasLimitedRange; /// If TRUE then important discovery making it possible for <see cref="Result.CreateDrillDownUrls"/> to make more suggestions.
        });

        /// <summary>
        /// TODO: Move <see cref="PropertyKeyForeignKeyAggregate"/> into separate file, together with <see cref="BaseInjector.GetForeignKeyAggregateKeys"/>
        /// 
        /// Called from <see cref="PropertyKeyMapper.MapEnumFinalize"/>
        /// 
        /// Actual values are later calculated by <see cref="CalculateForeignKeyAggregates"/> (note that this also sets <see cref="PropertyKeyAttribute.HasLimitedRange"/> as appropriate). 
        /// <param name="keys"></param>
        /// <returns></returns>
        [ClassMember(Description =
            "Generates -" + nameof(PropertyKeyForeignKeyAggregate) + "- for all aggregates that can automatically be deduced from standard AgoRapide information.\r\n" +
            "Will generate keys for -" + nameof(AggregationType.Count) + "- directly against foreign keys, and also keys for aggregates for all properties " +
            "for foreign entity which have -" + nameof(PropertyKeyAttribute.AggregationTypes) + "- set.\r\n")]
        public static List<PropertyKeyForeignKeyAggregate> GetForeignKeyAggregateKeys(List<PropertyKey> keys) {
            Util.AssertCurrentlyStartingUp();
            var retval = new List<PropertyKeyForeignKeyAggregate>();

            keys.Where(k => k.Key.A.ForeignKeyOf != null).ForEach(k => {
                k.Key.A.Parents.ForEach(p => { /// Note how multiple parents may share same foreign key. (Parents is guaranteed to be set now by <see cref="PropertyKeyAttributeEnriched.Initialize"/>.)
                                               /// IMPORTANT: DO NOT CALL p.GetChildProperties (That is, <see cref="Extensions.GetChildProperties"/> as value will be cached, making changes done her invisible)
                    keys.
                        Where(key => key.Key.IsParentFor(p) && (key.Key.CoreP == k.Key.CoreP || (key.Key.A.AggregationTypes != null && key.Key.A.AggregationTypes.Length > 0))).
                        ForEach(fp => { // Aggregate for all properties that are possible to aggregate over. 

                            // Added 14 Sep 2017. May have to relax a bit here though. 
                            InvalidTypeException.AssertEquals(fp.Key.A.Type, typeof(long), () => "Details: " + fp.ToString());

                            var aggregationTypes = k.Key.A.AggregationTypes.ToList();
                            if (fp.Key.CoreP == k.Key.CoreP && !aggregationTypes.Contains(AggregationType.Count)) aggregationTypes.Add(AggregationType.Count); // Always count number of foreign entities
                            aggregationTypes.ForEach(a => {
                                var foreignKeyAggregateKey = new PropertyKeyForeignKeyAggregate(
                                    a,
                                    p,
                                    k,
                                    fp,
                                    new PropertyKeyAttributeEnrichedDyn(
                                        new PropertyKeyAttribute(
                                                // Note that if there is only ONE foreignKey pointing towards entity, then identification for the foreign key can be shortened further.
                                                // (we can have (for Person) Count_Project instead of Count_Project_PersonId for instance)
                                                property: (
                                                    k.Key.A.ForeignKeyOf.ToStringVeryShort() + "_" +
                                                    a + "_" +
                                                    p.ToStringVeryShort() + "_" + fp.Key.PToString.Replace("CorrespondingInternalKey", "")). // Note removal of "CorrespondingInternalKey", resulting in shorter identification                                           
                                                    Replace(a + "_" + p.ToStringVeryShort() + "_" + p.ToStringVeryShort(), a + "_" + p.ToStringVeryShort() + "_"), // This replace will turn for instance Count_Project_ProjectLeaderPersonId into Count_Project_LeaderPersonId, that is, it shortens down aggregate keys when the P-enums repeat their parent-entity type.
                                                description: "-" + k.Key.A.ForeignKeyOf.ToStringVeryShort() + "- -" + a + "- for -" + p.ToStringVeryShort() + "- -" + fp.Key.PToString.Replace("CorrespondingInternalKey", "") + "-",
                                                longDescription: "",
                                                isMany: false
                                            ) {
                                            Parents = new Type[] { k.Key.A.ForeignKeyOf },
                                            Type = typeof(long), /// TODO: Maybe allow double also for aggregations?

                                            /// TODO: Note how <see cref="BaseEntity.ToHTMLTableRowHeading"/> / <see cref="BaseEntity.ToHTMLTableRow"/> uses
                                            /// TODO: <see cref="Extensions.GetChildPropertiesByPriority(Type, PriorityOrder)"/> which as of Sep 2017
                                            /// TODO: will not take into count access level as set here.
                                            /// TOOD: (while <see cref="BaseEntity.ToHTMLDetailed"/> uses <see cref="Extensions.GetChildPropertiesForUser"/>
                                            AccessLevelRead = AccessLevel.Relation // Important, make visible to user
                                        },
                                        (CoreP)PropertyKeyMapper.GetNextCorePId()
                                    )
                                );
                                foreignKeyAggregateKey.SetPropertyKeyWithIndexAndPropertyKeyAsIsManyParentOrTemplate(); // HACK!    
                                retval.Add(foreignKeyAggregateKey);
                            });
                        });
                });
            });
            return retval;
        }

        /// <summary>
        /// Called from <see cref="PropertyKeyMapper.MapEnumFinalize"/>  ????????????
        /// <param name="keys"></param>
        /// <returns></returns>
        [ClassMember(Description =
            "Generates expansion -" + nameof(PropertyKey) + "- for the given keys.\r\n" +
            "Example: For DateTime-field will generate Year, Month, Year_Month and so on, making later grouping easier.\r\n")]
        public static List<PropertyKeyForeignKeyAggregate> GetExpansionKeys(List<PropertyKey> keys) {
            Util.AssertCurrentlyStartingUp();
            var retval = new List<PropertyKeyForeignKeyAggregate>();
            return retval;
        }
    }

    //public class PropertyKeyExpansion : PropertyKey {

    //    public ExpansionType ExpansionType { get; private set; }

    //    /// <summary>
    //    /// T
    //    /// </summary>
    //    public PropertyKey SourceProperty { get; private set; }

    //}

    /// <summary>
    /// TODO: Move to separate file
    /// </summary>
    public enum ExpansionType {
        None,
        DateYear,
        DateYearMonth,
        DateYearQuarter,
        DateMonth,
        DateWeekday,
        DateAgeDays,
        DateAgeMonths,
        DateAgeYears
    }

    /// <summary>
    /// TODO: Move <see cref="PropertyKeyForeignKeyAggregate"/> into separate file, together with <see cref="BaseInjector.GetForeignKeyAggregateKeys"/>
    /// 
    /// Created by <see cref="BaseInjector"/> (called from <see cref="PropertyKeyMapper.MapEnumFinalize"/>), and by classes inheriting <see cref="BaseInjector"/>. 
    ///
    /// Some examples of aggregations:
    /// 
    /// 1) <see cref="AggregationType.Count"/>, <see cref="Person"/>, PersonP.Count_Project_LeaderId (based on foreignKey LeaderId in Projects)
    ///    Counting number of projects that a person is the leader of.
    ///
    /// 2) <see cref="AggregationType.Sum"/>, <see cref="Person"/>, PersonP.Sum_ProjectSumBudget (based on foreignKey in Projects and Property.Budget-property)
    ///    Sum of all projects related to this person.
    ///    
    /// NOTE: <see cref="AggregationKey"/> is not to be confused with <see cref="PropertyKeyForeignKeyAggregate"/>
    /// </summary>
    [Class(Description = "Represents aggregations sourced from all entities connected to a given entity and stored as -" + nameof(PropertyKey) + "- for the given entity. ")]
    public class PropertyKeyForeignKeyAggregate : PropertyKey {

        public AggregationType AggregationType { get; private set; }
        /// <summary>
        /// Must be specified since <see cref="SourceProperty"/> may have multiple values in <see cref="PropertyKeyAttribute.Parents"/>
        /// </summary>
        public Type SourceEntityType { get; private set; }

        [ClassMember(Description = "The -" + nameof(PropertyKeyAttribute.ForeignKeyOf) + "--property of the aggregation source entity (linking the given entity and the source entity together).")]
        public PropertyKey ForeignKeyProperty { get; private set; }

        [ClassMember(Description = "This is either identical to -" + nameof(ForeignKeyProperty) + "- or it can be any other property that can be aggregated.")]
        public PropertyKey SourceProperty { get; private set; }

        /// <summary>
        /// Should only be called at application startup through <see cref="PropertyKeyMapper"/>
        /// </summary>
        /// <param name="aggregationType"></param>
        /// <param name="sourceEntityType"></param>
        /// <param name="sourceProperty"></param>
        /// <param name="key"></param>
        public PropertyKeyForeignKeyAggregate(AggregationType aggregationType, Type sourceEntityType, PropertyKey foreignKeyProperty, PropertyKey sourceProperty, PropertyKeyAttributeEnriched key) : base(key) {
            Util.AssertCurrentlyStartingUp();
            AggregationType = aggregationType;
            SourceEntityType = sourceEntityType;
            ForeignKeyProperty = foreignKeyProperty;
            SourceProperty = sourceProperty;
        }
    }
}