using System;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AgoRapide.Core;
using System.Web.Http;
using AgoRapide.Database;
using AgoRapide.API;

namespace AgoRapide {

    /// <summary>
    /// TODO: Move to API-folder (no need to collect all <see cref="BaseEntity"/> in one place.
    /// </summary>
    [PropertyKey(
        Description = "Represents one API method, like \"Person/Add/{first_name}/{last_name}\"",
        AccessLevelRead = AccessLevel.Anonymous,
        AccessLevelWrite = AccessLevel.System
    )]
    public class APIMethod : ApplicationPart {

        /// <summary>
        /// Note about AgoRapide concepts in general:
        /// This property <see cref="Origin"/> is an example of how to expose properties more clearly (doing it directly from outside using 
        /// <see cref="BaseEntity.PVM"/> and 
        /// <see cref="BaseEntity.AddPropertyM{T}(T)"/> 
        /// would have worked just as well).
        /// 
        /// TODO: Make read-only!
        /// 
        /// TODO: MOVE THIS INTO MethodAttribute-class.
        /// </summary>
        public APIMethodOrigin Origin => PVM<APIMethodOrigin>();
        public string Implementator => PV<string>(CoreP.Implementator.A());

        /// <summary>
        /// Corresponds to  IHttpRoute.MapHttpRoute.defaults.Controller (although that one is without 'Controller' i the name).
        /// Name of type is guaranteed to end with 'Controller'.
        /// 
        /// Not set for <see cref="APIMethodOrigin.Autogenerated"/>
        /// </summary>
        public Type Controller { get; private set; }

        /// <summary>
        /// The method in the Controller implementing the API functionality
        /// Corresponds to IHttpRoute.MapHttpRoute.defaults.Action
        /// 
        /// Not set for <see cref="APIMethodOrigin.Autogenerated"/>
        /// </summary>
        public System.Reflection.MethodInfo ControllerMethod { get; private set; }

        public APIMethodAttribute A { get; private set; }

        /// <summary>
        /// TODO: When <see cref="PropertyKeyAttribute.IsMany"/> support is finished remove this specific method
        /// TODO and access straight from Properties-collection like method.PV{List{HTTPMethod}}()
        /// TODO: (need to implement how to transfer List to / from database)
        /// </summary>
        public List<HTTPMethod> HttpMethods { get; private set; }

        public bool RequiresAuthorization => PV<bool>(CoreP.RequiresAuthorization.A());

        /// <summary>
        /// Dummy constructor for use by <see cref="IDatabase.TryGetEntityById"/>. Object meant to be discarded immediately
        /// afterwards in <see cref="ApplicationPart.GetOrAdd{T}"/>. 
        /// DO NOT USE!
        /// </summary>
        public APIMethod() {
        }

        /// <summary>
        /// Used for <see cref="APIMethodOrigin.Autogenerated"/>-methods
        /// </summary>
        /// <param name="httpMethods"></param>
        /// <param name="routeSegments"></param>
        /// <param name="routeTemplate"></param>
        public APIMethod(Type entityType, APIMethodAttribute methodAttribute, List<HTTPMethod> httpMethods, List<RouteSegmentClass> routeSegments, List<PropertyKeyNonStrict> parameters, string routeTemplate) {
            _entityType = entityType; /// Null is relevant for <see cref="CoreAPIMethod.Configuration"/> ?? throw new NullReferenceException(nameof(entityType));
            A = methodAttribute ?? throw new NullReferenceException(nameof(methodAttribute));
            HttpMethods = httpMethods ?? throw new NullReferenceException(nameof(httpMethods));
            RouteSegments = routeSegments ?? throw new NullReferenceException(nameof(routeSegments));
            Parameters = parameters ?? throw new NullReferenceException(nameof(parameters));
            RouteTemplates = new List<string> { routeTemplate ?? throw new NullReferenceException(nameof(routeTemplate)) };
        }

        /// <summary>
        /// Used for <see cref="APIMethodOrigin.SemiAutogenerated"/>-methods
        /// </summary>
        /// <param name="controller"></param>
        /// <param name="controllerMethod"></param>
        /// <param name="methodAttribute"></param>
        /// <param name="httpMethods"></param>
        public APIMethod(Type controller, System.Reflection.MethodInfo controllerMethod, APIMethodAttribute methodAttribute, List<HTTPMethod> httpMethods) {
            Controller = controller ?? throw new ArgumentNullException(nameof(controller));
            if (!Controller.ToStringShort().EndsWith("Controller")) throw new InvalidControllernameException("'" + controller.ToStringShort() + "' does not end with 'Controller'");
            ControllerMethod = controllerMethod ?? throw new ArgumentNullException(nameof(controllerMethod));
            A = methodAttribute ?? throw new NullReferenceException(nameof(methodAttribute));
            HttpMethods = httpMethods ?? throw new ArgumentNullException(nameof(httpMethods));

            var detailer1 = new Func<string>(() => "\r\nerrorDetails: " + ToString());

            RouteSegments = new List<RouteSegmentClass>();
            if (A.S1 != null) RouteSegments.Add(new RouteSegmentClass(nameof(A.S1), A.S1, detailer1));
            if (A.S2 != null) RouteSegments.Add(new RouteSegmentClass(nameof(A.S2), A.S2, detailer1));
            if (A.S3 != null) RouteSegments.Add(new RouteSegmentClass(nameof(A.S3), A.S3, detailer1));
            if (A.S4 != null) RouteSegments.Add(new RouteSegmentClass(nameof(A.S4), A.S4, detailer1));
            if (A.S5 != null) RouteSegments.Add(new RouteSegmentClass(nameof(A.S5), A.S5, detailer1));
            if (A.S6 != null) RouteSegments.Add(new RouteSegmentClass(nameof(A.S6), A.S6, detailer1));
            if (A.S7 != null) RouteSegments.Add(new RouteSegmentClass(nameof(A.S7), A.S7, detailer1));
            if (A.S8 != null) RouteSegments.Add(new RouteSegmentClass(nameof(A.S8), A.S8, detailer1));
            if (A.S9 != null) RouteSegments.Add(new RouteSegmentClass(nameof(A.S9), A.S9, detailer1));

            switch (A.CoreMethod) {
                case CoreAPIMethod.RootIndex:
                case CoreAPIMethod.GenericMethod:
                    if (RouteSegments.Count > 0) throw new MethodAttributeInitialisationException(
                        nameof(RouteSegments) + " (like S1, S2, S3 ...) are not allowed for " + typeof(CoreAPIMethod) + "." + A.CoreMethod + ". " +
                        nameof(RouteSegments) + ".Count: " + RouteSegments.Count + ". " +
                        detailer1.Result("Details: "));
                    if (!string.IsNullOrEmpty(A.RouteTemplate)) throw new MethodAttributeInitialisationException(
                        nameof(A.RouteTemplate) + " is not allowed for " + typeof(CoreAPIMethod) + "." + A.CoreMethod + ". " +
                        nameof(A.RouteTemplate) + ": " + A.RouteTemplate + ". " +
                        (A.CoreMethod == CoreAPIMethod.GenericMethod ? ("For " + A.CoreMethod + " it will default to " + typeof(ConfigurationAttribute) + "." + nameof(ConfigurationAttribute.GenericMethodRouteTemplate) + " = " + Util.Configuration.A.GenericMethodRouteTemplate) : "") + ". " +
                        detailer1()); break;
                default:
                    break;// OK
            }

            if (!string.IsNullOrEmpty(A.RouteTemplate)) {
                // TODO: Implement parsing of traditional WebAPI template
                throw new NotImplementedException(nameof(APIMethodAttribute) + "." + nameof(APIMethodAttribute.RouteTemplate) + ", " + detailer1());
            }

            Parameters = new List<PropertyKeyNonStrict>();

            if (RouteSegments.Count == 0) {
                switch (A.CoreMethod) {
                    case CoreAPIMethod.RootIndex:
                        RouteTemplates = new List<string> { "" };
                        return; // Initialization is now complete.
                    case CoreAPIMethod.GenericMethod:
                        RouteTemplates = new List<string> { Util.Configuration.A.GenericMethodRouteTemplate }; // Usually "{*url}"
                        return; // Initialization is now complete.
                    default:
                        throw new MethodInitialisationException("No " + nameof(APIMethodAttribute) + "." + nameof(A.RouteTemplate) + ", no " + nameof(RouteSegments) + " and unknown " + nameof(CoreAPIMethod) + " (" + A.CoreMethod + "). Possible resolution: Remove attribute " + A.GetType().ToString() + " if not needed" + detailer1());
                }
            }

            // Continue with setting RouteTemplates, Parameters and other values:
            var parameters = ControllerMethod.GetParameters().ToList();
            parameters.ForEach(p => {
                if (!p.ParameterType.Equals(typeof(string))) throw new InvalidObjectTypeException(p.ParameterType, "Parameter " + p.ToString() + ". All parameters must have type " + typeof(string) + detailer1());
            });
            var routeTemplate = new System.Text.StringBuilder();

            var restParameters = parameters.ToDictionary(p => p.Name);
            // Check that ordering of parameters is the same, and that the names are equivalent
            RouteSegments.ForEach(s => {
                var detailer2 = new Func<string>(() => detailer1() + "\r\nRouteSegment: [" + A.GetType().ToString() + "(" + s.SegmentName + ")]");

                if (s.Type != null) {
                    routeTemplate.Append("/" + s.Type.ToStringVeryShort());
                    if (EntityType != null) throw new MethodInitialisationException(
                        "Duplicate type-definition\r\n" +
                        "(both " + s.Type + " and " + EntityType + " found)\r\n" +
                        // The first mistake (s.Type.IsEnum) is more common
                        (s.Type.IsEnum ? ("Did you write typeof(" + s.Type.ToStringShort() + ") when you really intended " + nameof(CoreP) + "." + s.Type.ToStringVeryShort() + "?\r\n") : "") +
                        // The second mistake (EntityType.IsEnum) less common
                        (EntityType.IsEnum ? ("Did you write typeof(" + EntityType.ToStringShort() + ") when you really intended " + nameof(CoreP) + "." + EntityType.ToStringVeryShort() + "?\r\n") : "") +
                        detailer2());
                    _entityType = s.Type;
                } else if (s.Parameter != null) {
                    var p = s.Parameter.Key;
                    if (p.A.Parents != null && EntityType != null && !p.IsParentFor(EntityType)) throw new MethodInitialisationException(
                            "Incompatible types given for " +
                            p.GetType().ToString() + "-segment (" + EntityType + ") and " +
                            typeof(CoreP).ToString() + "." + p.CoreP.ToString() + " (" + p.A.Parents + ")\r\n" +
                            "You can not have " + typeof(CoreP).ToString() + "." + p.CoreP + " " +
                            "as parameter for operations involving entities of type " + EntityType + " " +
                            "because !" + nameof(p.IsParentFor) + "(" + EntityType + ")" + detailer2());

                    if (restParameters.Count == 0) throw new MethodInitialisationException(
                        "Too few parameters defined in source code.\r\n" +
                        "Corresponding parameter " + p.PExplained + " for RouteSegment " +
                        "is missing for method " + ControllerMethod.Name + detailer2());
                    if (!restParameters.TryGetValue(p.PToString, out _)) throw new MethodInitialisationException(
                        "Corresponding parameter " + p.PExplained + " for RouteSegment " +
                        "is missing (or wrongly named) for method " + ControllerMethod.Name + ".\r\n" +
                        "Is one of the following mis-named: " + restParameters.KeysAsString() + "\r\n?\r\n" +
                        detailer2());
                    if (Parameters.Any(t => t.Key.CoreP.Equals(p.CoreP))) throw new MethodInitialisationException("Duplicate parameter " + typeof(CoreP).ToString() + "." + p.CoreP + " given" + detailer2());
                    Parameters.Add(s.Parameter);
                    restParameters.Remove(p.PToString);
                    routeTemplate.Append("/{" + p.PToString + "}");
                    // break;
                    // case RouteSegment es:
                } else if (s.String != null) {
                    routeTemplate.Append("/" + s.String);
                } else {
                    throw new RouteSegmentClass.InvalidRouteSegmentClassException("Did not recognize any of the supposed required types" + detailer2());
                }
            });
            if (restParameters.Count > 0) throw new MethodInitialisationException("The following parameters does not have corresponding [" + A.GetType().ToString() + "(Sx = " + typeof(CoreP).ToString() + ".yyy)] initialisations: " + string.Join(", ", restParameters.Keys) + detailer1);
            var strRouteTemplate = routeTemplate.ToString();
            if (strRouteTemplate.Length > 0 && strRouteTemplate.StartsWith("/")) strRouteTemplate = strRouteTemplate.Substring(1);
            RouteTemplates = new List<string> { strRouteTemplate };
        }

        /// <summary>
        /// Consists of controller = Controller and action = MethodName
        /// </summary>
        public object Defaults {
            get {
                if (Origin == APIMethodOrigin.Autogenerated) throw new InvalidEnumException(Origin, ToString());
                return new {
                    controller = Controller.ToStringShort().Replace("Controller", ""),
                    action = ControllerMethod.Name
                };
            }
        }

        ///// <summary>
        ///// Used for internal indexation for identification
        ///// TODO: InternalKey and Name should be merged together
        ///// TODO: (but maybe InternalKey is needed as a filename-safe variant?)
        ///// </summary>
        //private string _internalKey => Controller + "." + ControllerMethod.Name;

        /// <summary>
        /// TODO: Turn this into a single string since overloads are now handled by the 
        /// TODO: <see cref="BaseController.AgoRapideGenericMethod"/> concept.
        /// 
        /// Guaranteed always set with at least one value (but for <see cref="CoreAPIMethod.RootIndex"/> the value will usually be empty)
        /// 
        /// REST URL syntax as used by Microsoft .NET WebAPI like Person/Add/{first_name}/{last_name}
        /// For <see cref="CoreAPIMethod.GenericMethod"/> it is usually {*url} 
        /// 
        /// Note that <see cref="Util.Configuration"/>.<see cref="ConfigurationAttribute.ApiPrefix"/> (normally "api/") is not present here. 
        /// It is added later by <see cref="APIMethodMapper.MapHTTPRoutes"/>
        /// </summary>
        public List<string> RouteTemplates { get; private set; }

        /// <summary>
        /// Inserts <paramref name="parameters"/> into <see cref="RouteTemplates"/> according to <see cref="PropertyKeyAttributeEnriched.ConvertObjectToString"/>
        /// </summary>
        /// <param name="parameters"></param>
        /// <returns></returns>
        public string GetAPICommand(params object[] parameters) {
            if (parameters.Length != Parameters.Count) throw new InvalidCountException(nameof(parameters) + ".Length (" + parameters.Length + ") != " + nameof(Parameters) + ".Count (" + Parameters.Count + ") for " + ToString());
            var retval = RouteTemplates[0];
            for (var i = 0; i < parameters.Length; i++) {
                if (Parameters.Count <= i) return retval;
                var key = "{" + Parameters[i].Key.PToString + "}";
                var next = retval.Replace(key, Parameters[i].Key.ConvertObjectToString(parameters[i]));
                if (next.Equals(retval)) throw new MethodInitialisationException(key + " not found for " + ToString());
                retval = next;
            }
            return retval;
        }

        /// <summary>
        /// Try to set Origin and Controller / ControllerMethod in a more orderly fashion, so we can remove some
        /// unnecessary checks here (especially origin)
        /// </summary>
        /// <returns></returns>
        public override string ToString() =>
            (Properties != null && Properties.ContainsKey(CoreP.APIMethodOrigin) ? (Origin.ToString() + ", ") : "") +
            (RouteTemplates != null && RouteTemplates.Count > 0 ? (RouteTemplates[0] + ", ") : "") +
            (Controller != null ? (Controller.ToStringShort() + ".") : "") +
            (ControllerMethod != null ? (ControllerMethod.Name + ", ") : "") +
            (A != null && A.CoreMethod != CoreAPIMethod.None ? (nameof(CoreAPIMethod) + "." + A.CoreMethod) : "");

        public class MethodInitialisationException : ApplicationException {
            public MethodInitialisationException(string message) : base(message) { }
        }

        public class InvalidRouteTemplateException : ApplicationException {
            public InvalidRouteTemplateException(string message) : base(message) { }
        }

        /// <summary>
        /// TODO: MOVE TO SEPARATE DOCUMENTATOR CLASS!
        /// 
        /// Inserts HTML links to methods within the HTML given
        /// See also InsertDocumentationURLs 
        /// </summary>
        /// <param name="html">
        /// Tip: Use the shortest route templates, like -Person/Add- since the documentation URL is the same for all overloads.
        /// </param>
        /// <returns></returns>
        public static string InsertDocumentationHTMLLinks(string html) {
            if (string.IsNullOrEmpty(html)) return html;
            throw new NotImplementedException();
            // AllMethods.ForEach(r => r.RouteTemplates.ForEach(template => html = html.Replace("-" + template + "-", r.DocumentationLink)));
        }

        /// <summary>
        /// TODO: MOVE TO SEPARATE DOCUMENTATOR CLASS!
        /// 
        /// Inserts URL to methods into text. 
        /// See also InsertDocumentationHTMLLinks
        /// 
        /// All occurrences of route templates like -Person/Add- or -Person/Add/{first_name}- will be
        /// replaced with a URL to that method's corresponding documentation.
        /// </summary>
        /// <param name="text">
        /// Tip: Use the shortest route templates, like -Person/Add- since the documentation URL is the same for all overloads.        /// </param>
        /// <returns></returns>
        public static string InsertDocumentationURLs(string text) => throw new NotImplementedException();

        private Type _entityType;
        public Type EntityType => _entityType ?? (_entityType = TryGetPV<Type>(CoreP.EntityType.A(), out var retval) ? retval : null); // Set in-memory, later read from database

        public List<PropertyKeyNonStrict> Parameters { get; private set; }

        /// <summary>
        /// Set by <see cref="CreateSemiAutogeneratedMethods"/>
        /// </summary>
        protected static List<APIMethod> _allMethods = null;
        /// <summary>
        /// TODO: Add GetByName / GetByInternalKey, GetByCoreMethod and corresponding TryGet...-methods
        /// </summary>
        public static List<APIMethod> AllMethods => _allMethods ?? throw new NullReferenceException(nameof(_allMethods) + ", Call " + nameof(CreateSemiAutogeneratedMethods) + " first");

        /// <summary>
        /// Methods ignored because <see cref="APIMethodAttribute.Environment"/> does not match current <see cref="ConfigurationAttribute.Environment"/>
        /// </summary>
        public static List<APIMethod> IgnoredMethods = new List<APIMethod>();

        /// <summary>
        /// Set by <see cref="CreateSemiAutogeneratedMethods"/>
        /// Key is <see cref="BaseEntity.Name"/> which again is set as method.Controller.ToStringShort() + "." + method.ControllerMethod.Name
        /// TODO: Add GetByName / GetByInternalKey, GetByCoreMethod and corresponding TryGet...-methods
        /// </summary>
        protected static Dictionary<string, APIMethod> _allMethodsByControllerAndMethodName;
        /// <summary>
        /// Set by <see cref="CreateSemiAutogeneratedMethods"/>
        /// TODO: Add GetByName / GetByInternalKey, GetByCoreMethod and corresponding TryGet...-methods
        /// </summary>
        // protected static SortedDictionary<string, APIMethod> _allMethodsByName = null;

        public static APIMethod GetByControllerAndMethodName(Type controller, string controllerMethodName) => TryGetByControllerAndMethodName(controller, controllerMethodName, out var retval) ? retval : throw new MethodNotFoundException("Method '" + controller + "." + controllerMethodName + "' not found");
        public static bool TryGetByControllerAndMethodName(Type controller, string controllerMethodName, out APIMethod method) {
            var dummy = AllMethods;
            return _allMethodsByControllerAndMethodName.TryGetValue(controller.ToStringShort() + "." + controllerMethodName, out method);
        }

        public static APIMethod GetByCoreMethodAndEntityType(CoreAPIMethod coreMethod, Type entityType) => TryGetByCoreMethodAndEntityType(coreMethod, entityType, out var retval) ? retval : throw new MethodNotFoundException(coreMethod, entityType);
        protected static ConcurrentDictionary<string, APIMethod> _allMethodsByCoreMethodAndEntityType = new ConcurrentDictionary<string, APIMethod>();
        /// <summary>
        /// 
        /// </summary>
        /// <param name="coreMethod"></param>
        /// <param name="entityType">May be null, for instance for <see cref="CoreAPIMethod.ExceptionDetails"/></param>
        /// <param name="method"></param>
        /// <returns></returns>
        public static bool TryGetByCoreMethodAndEntityType(CoreAPIMethod coreMethod, Type entityType, out APIMethod method) => (method = _allMethodsByCoreMethodAndEntityType.GetOrAdd(coreMethod.ToString() + "_" + (entityType?.ToString() ?? ""), k => {
            //if (coreMethod == CoreMethod.Configuration) {
            //    var a = 1;
            //}
            if (entityType != null && typeof(Property).IsAssignableFrom(entityType)) entityType = typeof(Property); /// This adjustment is necessary in cases where entityType is an instance of <see cref="PropertyT{T}"/>.
            //if (entityType != null && CoreMethod.EntityIndex.Equals(coreMethod)) {
            //    coreMethod = CoreMethod.Configuration;
            //    entityType = null; /// Typical example when <see cref="Property"/> uses <see cref="Property.Parent"/> in order to create link to the parent
            //}
            return AllMethods.SingleOrDefault(m => m.A.CoreMethod == coreMethod && ((entityType == null && m.EntityType == null) || (entityType != null && entityType.Equals(m.EntityType))), () => nameof(coreMethod) + ": " + coreMethod + ", " + nameof(entityType) + ": " + (entityType?.ToStringShort() ?? "[NULL]"));
        })) != null;

        /// <summary>
        /// This consists of the values for <see cref="APIMethodAttribute.S1"/> to <see cref="APIMethodAttribute.S9"/>. Set by <see cref="CreateSemiAutogeneratedMethods"/>
        /// </summary>
        public List<RouteSegmentClass> RouteSegments { get; private set; }

        protected static Dictionary<string, APIMethod> _allMethodsByRouteTemplate;
        /// <summary>
        /// Constructs <see cref="APIMethodOrigin.SemiAutogenerated"/>-methods.
        /// </summary>
        /// <param name="controllers"></param>
        /// <param name="attributeClassesSignifyingRequiresAuthorization">
        /// Used to set <see cref="APIMethod.RequiresAuthorization"/>.
        /// Typical values would be type of <see cref="System.Web.Http.AuthorizeAttribute"/> or 
        /// your own types like AgoRapideSample.BasicAuthenticationAttribute
        /// </param>
        /// <returns></returns>
        public static void CreateSemiAutogeneratedMethods(List<Type> controllers, List<Type> attributeClassesSignifyingRequiresAuthorization, IDatabase db) {
            _allMethods = new List<APIMethod>();
            controllers.ForEach(controller => {
                controller.GetMethods().ForEach(methodInfo => {
                    var ma = Attribute.GetCustomAttribute(methodInfo, typeof(APIMethodAttribute)) as APIMethodAttribute;
                    if (ma == null) return; // OK, just ignore this method
                    var detailer1 = new Func<string>(() => ". errorDetails: " + controller.ToString() + "." + methodInfo.Name);

                    var method = new APIMethod(
                        controller: controller,
                        controllerMethod: methodInfo,
                        methodAttribute: ma,

                        /// TODO: When <see cref="PropertyKeyAttribute.IsMany"/> support is finished remove this specific method
                        /// TODO and access straight from Properties-collection like method.PV{List{HTTPMethod}}()
                        /// TODO: (need to implement how to transfer List to / from database)
                        httpMethods: new Func<List<HTTPMethod>>(() => {
                            var r = new List<HTTPMethod>();
                            if (null != Attribute.GetCustomAttribute(methodInfo, typeof(HttpGetAttribute))) r.Add(HTTPMethod.GET);
                            if (null != Attribute.GetCustomAttribute(methodInfo, typeof(HttpPostAttribute))) r.Add(HTTPMethod.POST);
                            // DELETE and PUT may be added if desired.
                            return r;
                        })()
                    );
                    /// TODO: Find mechanism for setting invalid for methods no longer relevant (that is, old methods resisting in database
                    /// TODO: no longer relevant since ConnectMethodWithDatabase is not called for them)
                    FilterConnectWithDatabaseAndAddMethod(
                        method: method,
                        origin: APIMethodOrigin.SemiAutogenerated,
                        requiresAuthorization: attributeClassesSignifyingRequiresAuthorization.Any(t => null != Attribute.GetCustomAttribute(methodInfo, t)),
                        db: db);
                });
            });
            _allMethods.ForEach(r => { // Assert valid RouteTemplates since they are set multiple places above:
                if (r.RouteTemplates == null) throw new MethodInitialisationException(nameof(RouteTemplates) + " == null for " + r.ToString());
                if (r.RouteTemplates.Count == 0) throw new MethodInitialisationException(nameof(RouteTemplates) + ".Count == 0 for " + r.ToString());
                r.RouteTemplates.ForEach(rt => {
                    if (rt == null) throw new MethodInitialisationException("One of the " + nameof(RouteTemplates) + " == null for " + r.ToString() + ". All " + nameof(RouteTemplates) + ": " + string.Join(",", r.RouteTemplates));
                    if (rt.Contains("//")) throw new MethodInitialisationException("One of the " + nameof(RouteTemplates) + " (" + rt + ") Contains (\"//\") for " + r.ToString() + ". All " + nameof(RouteTemplates) + ": " + string.Join(",", r.RouteTemplates));
                    if (rt.StartsWith("/")) throw new MethodInitialisationException("One of the " + nameof(RouteTemplates) + " (" + rt + ") StartsWith(\"/\") for " + r.ToString() + ". All " + nameof(RouteTemplates) + ": " + string.Join(",", r.RouteTemplates));
                });

            });

            /// TODO: Add GetByName / GetByInternalKey, GetByCoreMethod and corresponding TryGet...-methods
            _allMethodsByControllerAndMethodName = new Dictionary<string, APIMethod>();
            _allMethodsByRouteTemplate = new Dictionary<string, APIMethod>();
            // _allMethodsByName = new SortedDictionary<string, APIMethod>();
            _allMethods.ForEach(m => {
                _allMethodsByControllerAndMethodName.AddValue(m.Implementator, m, () => "Duplicate " + nameof(Implementator) + " (" + m.Implementator + ") has already been added to collection " + nameof(_allMethodsByControllerAndMethodName));
                _allMethodsByRouteTemplate.AddValue(m.RouteTemplates[0], m, () => "Duplicate " + nameof(m.RouteTemplates) + "[0] (" + m.RouteTemplates[0] + ") has already been added to collection " + nameof(_allMethodsByRouteTemplate));
                //if (_allMethodsByName.ContainsKey(m.Name)) throw new KeyAlreadyExistsException("Duplicate " + nameof(m.Name) + " (" + m.Name + ") has already been added to collection " + nameof(_allMethodsByName));
                //_allMethodsByName.Add(m.Name, m);
            });
        }

        /// <summary>
        /// Constructs <see cref="APIMethodOrigin.Autogenerated"/>-methods.        
        /// Adds these to <see cref="AllMethods"/>. 
        /// 
        /// TODO: MAYBE MOVE THIS METHOD SOMEWHERE ELSE
        /// TODO: DECIDE BETTER WHEN / HOW TO CALL THIS
        /// </summary>
        /// <param name="types">
        /// List of entities for which client wants standardised methods like Person/{id}, Person/{id}/AddProperty/{key}/{value}
        /// </param>
        public static void CreateAutogeneratedMethods(List<Type> types, IDatabase db) {
            if (_allMethods == null) throw new NullReferenceException(nameof(_allMethods) + ". Resolution: " + nameof(CreateSemiAutogeneratedMethods) + " must be called before " + nameof(CreateAutogeneratedMethods));

            var connector = new Action<APIMethod, bool>((method, requiresAuthorization) => {
                /// TODO: Find mechanism for setting invalid for methods no longer relevant (that is, old methods resisting in database
                /// TODO: no longer relevant since ConnectMethodWithDatabase is not called for them)
                if (_allMethodsByRouteTemplate.TryGetValue(method.RouteTemplates[0], out var existing)) throw new MethodInitialisationException(
                    method.RouteTemplates[0] + " is already implemented by " + existing.Implementator + ".\r\n" +
                    "You must either remove that implementation or remove type " + method.EntityType.ToStringShort() + " as parameter to " + System.Reflection.MethodBase.GetCurrentMethod().Name + ".\r\n" +
                    "Details for existing method: " + existing.ToString() + ".\r\n" +
                    "Details for " + APIMethodOrigin.Autogenerated + " method: " + method.ToString());
                FilterConnectWithDatabaseAndAddMethod(
                    method: method,
                    origin: APIMethodOrigin.Autogenerated,
                    requiresAuthorization: requiresAuthorization,
                    db: db);
            });

            /// Creates <see cref="CoreAPIMethod.AddEntity"/> like Person/Add/{email}/{password}
            var addEntityCreator = new Action<Type>(t => { // TODO: There appears to be too much duplicated code in the creators methods here
                var detailer = new Func<string>(() => APIMethodOrigin.Autogenerated + " " + CoreAPIMethod.AddEntity + " attempt for " + t.ToStringDB());
                var obligatoryParameters = t.GetObligatoryChildProperties();
                var routeSegments = new List<RouteSegmentClass> {
                    new RouteSegmentClass(t.ToStringVeryShort(), t, detailer),
                    new RouteSegmentClass("Add", "Add", detailer),
                };
                obligatoryParameters.ForEach(p => routeSegments.Add(new RouteSegmentClass(p.Value.Key.PToString, p.Value, detailer)));
                var method = new APIMethod(
                    entityType: t,
                    methodAttribute: new APIMethodAttribute {
                        CoreMethod = CoreAPIMethod.AddEntity,
                        Description =
                            "Adds an entity of type " + t.ToStringShort() + ".",
                        AccessLevelUse = t.GetClassAttribute().AccessLevelWrite // Use of method equals writing of entity (creation)
                    },
                    /// TODO: MAKE SURE HTTP-METHODS ARE STORED IN DATABASE (keeping historical track of changes)
                    httpMethods: new List<HTTPMethod> { HTTPMethod.GET },
                    routeSegments: routeSegments,
                    parameters: obligatoryParameters.Values.Select(p =>
                        !p.Key.A.IsMany ?
                            (PropertyKeyNonStrict)p :
                            throw new PropertyKeyWithIndex.InvalidPropertyKeyException(nameof(PropertyKeyAttribute.IsMany) + " invalid in combination with " + nameof(PropertyKeyAttribute.IsObligatory) + ".\r\nDetails: " + CoreAPIMethod.AddEntity + " for " + t + "\r\nDetails for " + nameof(p.Key) + ": " + p.Key.ToString())
                        ).ToList(),
                    routeTemplate: t.ToStringVeryShort() + "/Add" + string.Join("", obligatoryParameters.Select(p => "/{" + p.Value.Key.PToString + "}"))
                    );
                connector(method, true);
            });

            /// Creates <see cref="CoreAPIMethod.EntityIndex"/> like Person/{id}
            var entityIndexCreator = new Action<Type>(t => { // TODO: There appears to be too much duplicated code in the creators methods here
                var detailer = new Func<string>(() => APIMethodOrigin.Autogenerated + " " + CoreAPIMethod.EntityIndex + " attempt for " + t.ToStringDB());
                var method = new APIMethod(
                    entityType: t,
                    methodAttribute: new APIMethodAttribute {
                        CoreMethod = CoreAPIMethod.EntityIndex,
                        Description =
                            "Shows entities of type " + t.ToStringShort() + " as identified by {" + CoreP.QueryId + "}.\r\n" +
                            "Usually {" + CoreP.QueryId + "} will be an integer but note how even multiple entities may be identified.",
                        AccessLevelUse = t.Equals(typeof(BaseEntity)) ?

                            /// NOTE: SOME entities may have <see cref="AccessLevel.Anonymous"/> and therefore the method itself must be 
                            /// NOTE: available for <see cref="AccessLevel.Anonymous"/>. The rationale is that we want to be able to link with
                            /// NOTE: api/Entity/{QueryId} whenever we see a <see cref="CoreP.DBId"/>-property without knowing what type of entity it is.
                            /// ----
                            /// TODO: Complete <see cref="IDatabase.TryVerifyAccess"/> in order for this to not be a security problem.
                            /// ----
                            /// NOTE: As of Apr 2017 similar exception has not been made for other <see cref="CoreAPIMethod"/>.
                            AccessLevel.Anonymous :

                            // In all other cases use of method equals reading of entity and we can se access equivalent to that set for the entity class
                            t.GetClassAttribute().AccessLevelRead
                    },
                    /// TODO: MAKE SURE HTTP-METHODS ARE STORED IN DATABASE (keeping historical track of changes)
                    httpMethods: new List<HTTPMethod> { HTTPMethod.GET },
                    routeSegments: new List<RouteSegmentClass> {
                        new RouteSegmentClass(t.ToStringVeryShort(), t, detailer),
                        new RouteSegmentClass(CoreP.QueryId.ToString(), CoreP.QueryId , detailer)
                    },
                    parameters: new List<PropertyKeyNonStrict> { CoreP.QueryId.A() },
                    routeTemplate: t.ToStringVeryShort() + "/{" + CoreP.QueryId + "}" // Do not use M here!
                    );
                // TODO: Create a configuration parameter deciding whether API-documentation should be available without authorization.
                // TODO: We could also change this between production and test, for instance tightening down access to 
                // TODO: API-documentation in test, while having anonymous access in production, hiding new features until launched.
                connector(method, !typeof(ApplicationPart).IsAssignableFrom(method.EntityType)); /// Note how <see cref="ApplicationPart"/> like <see cref="ClassAndMethod"/>, <see cref="EnumClass"/> and <see cref="APIMethod"/> can be read-accessed (queried) without authorization (that is, the API documentation is common available)
            });

            /// Creates <see cref="CoreAPIMethod.UpdateProperty"/> like Person/{id}/AddProperty/{id}/{value]
            var updatePropertyCreator = new Action<Type>(t => { // TODO: There appears to be too much duplicated code in the creators methods here
                var detailer = new Func<string>(() => APIMethodOrigin.Autogenerated + " " + CoreAPIMethod.UpdateProperty + " attempt for " + t.ToStringDB());
                var method = new APIMethod(
                    entityType: t,
                    methodAttribute: new APIMethodAttribute {
                        CoreMethod = CoreAPIMethod.UpdateProperty,
                        Description =
                            "Adds property for entities of type " + t.ToStringShort() + " as identified by {" + CoreP.QueryId + "}.\r\n" +
                            "Usually {" + CoreP.QueryId + "} will be an integer but note how even multiple entities may be identified.",
                        AccessLevelUse = t.GetClassAttribute().AccessLevelWrite // Use of method equals writing to entity
                    },
                    /// TODO: MAKE SURE HTTP-METHODS ARE STORED IN DATABASE (keeping historical track of changes)
                    httpMethods: new List<HTTPMethod> { HTTPMethod.GET },
                    routeSegments: new List<RouteSegmentClass> {
                        new RouteSegmentClass(t.ToStringVeryShort(), t, detailer),
                        new RouteSegmentClass(nameof(CoreP.QueryId), CoreP.QueryId , detailer),
                        new RouteSegmentClass(CoreAPIMethod.UpdateProperty.ToString(), CoreAPIMethod.UpdateProperty.ToString(), detailer),
                        new RouteSegmentClass(nameof(CoreP.Key), CoreP.Key , detailer),
                        new RouteSegmentClass(nameof(CoreP.Value), CoreP.Value , detailer)
                    },
                    parameters: new List<PropertyKeyNonStrict> {
                        CoreP.QueryId.A(),
                        CoreP.Key.A(),
                        CoreP.Value.A()
                    },
                    routeTemplate: t.ToStringVeryShort() + "/{" + CoreP.QueryId + "}/" + CoreAPIMethod.UpdateProperty.ToString() + "/{" + CoreP.Key + "}/{" + CoreP.Value + "}" // Do not use M here!
                    );
                connector(method, true);
            });

            /// Creates <see cref="CoreAPIMethod.PropertyOperation"/> like Person/{id}/AddProperty/{id}/{value]
            var propertyOperationCreator = new Action<Type>(t => { // TODO: There appears to be too much duplicated code in the creators methods here
                var detailer = new Func<string>(() => APIMethodOrigin.Autogenerated + " " + CoreAPIMethod.PropertyOperation + " attempt for " + t.ToStringDB());
                var method = new APIMethod(
                    entityType: t,
                    methodAttribute: new APIMethodAttribute {
                        CoreMethod = CoreAPIMethod.PropertyOperation,
                        Description =
                            "Operates on property as identified by {" + CoreP.QueryId + "} with {" + nameof(PropertyOperation) + "} one of " + string.Join(", ", Util.EnumGetValues<PropertyOperation>()) + ".\r\n" +
                            "Usually {" + CoreP.QueryId + "} will be an integer but note how even multiple entities may be identified.",
                        AccessLevelUse = t.GetClassAttribute().AccessLevelWrite // Use of method equals writing to entity
                    },
                    /// TODO: MAKE SURE HTTP-METHODS ARE STORED IN DATABASE (keeping historical track of changes)
                    httpMethods: new List<HTTPMethod> { HTTPMethod.GET },
                    routeSegments: new List<RouteSegmentClass> {
                        new RouteSegmentClass(t.ToStringVeryShort(), t, detailer),
                        new RouteSegmentClass(nameof(CoreP.QueryId), CoreP.QueryId , detailer),
                        new RouteSegmentClass(nameof(CoreP.PropertyOperation), CoreP.PropertyOperation , detailer)
                    },
                    parameters: new List<PropertyKeyNonStrict> {
                        CoreP.QueryId.A(),
                        CoreP.PropertyOperation.A()
                    },
                    routeTemplate: t.ToStringVeryShort() + "/{" + CoreP.QueryId + "}/{" + CoreP.PropertyOperation + "}" // Do not use M here!
                );
                connector(method, true);
            });

            /// Creates <see cref="CoreAPIMethod.History"/> like Person/{id}/History and Person/{id}/History
            var historyCreator = new Action<Type>(t => { // TODO: There appears to be too much duplicated code in the creators methods here
                var detailer = new Func<string>(() => APIMethodOrigin.Autogenerated + " " + CoreAPIMethod.History + " attempt for " + t.ToStringDB());
                var method = new APIMethod(
                    entityType: t,
                    methodAttribute: new APIMethodAttribute {
                        CoreMethod = CoreAPIMethod.History,
                        Description =
                            "Shows history for entity identified by {" + CoreP.IntegerQueryId + "}.",
                        AccessLevelUse = t.GetClassAttribute().AccessLevelRead // Use of method equals writing to entity
                    },
                    /// TODO: MAKE SURE HTTP-METHODS ARE STORED IN DATABASE (keeping historical track of changes)
                    httpMethods: new List<HTTPMethod> { HTTPMethod.GET },
                    routeSegments: new List<RouteSegmentClass> {
                        new RouteSegmentClass(t.ToStringVeryShort(), t, detailer),
                        new RouteSegmentClass(nameof(CoreP.IntegerQueryId), CoreP.IntegerQueryId , detailer),
                        new RouteSegmentClass(nameof(CoreAPIMethod.History), CoreAPIMethod.History.ToString() , detailer)
                    },
                    parameters: new List<PropertyKeyNonStrict> {
                        CoreP.IntegerQueryId.A()
                    },
                    routeTemplate: t.ToStringVeryShort() + "/{" + CoreP.IntegerQueryId + "}/" + CoreAPIMethod.History // Do not use M here!
                    );
                connector(method, true);
            });


            /// Creates <see cref="CoreAPIMethod.Configuration"/>
            {
                var detailer = new Func<string>(() => APIMethodOrigin.Autogenerated + " " + CoreAPIMethod.Configuration);
                var method = new APIMethod(
                    entityType: null,
                    methodAttribute: new APIMethodAttribute {
                        CoreMethod = CoreAPIMethod.Configuration,
                        Description = CoreAPIMethod.Configuration.GetAgoRapideAttributeT().A.Description,
                        AccessLevelUse = AccessLevel.Admin
                    },
                    /// TODO: MAKE SURE HTTP-METHODS ARE STORED IN DATABASE (keeping historical track of changes)
                    httpMethods: new List<HTTPMethod> { HTTPMethod.GET },
                        routeSegments: new List<RouteSegmentClass> {
                        new RouteSegmentClass(CoreAPIMethod.Configuration.ToString(), CoreAPIMethod.Configuration.ToString(), detailer)
                    },
                    parameters: new List<PropertyKeyNonStrict>(),
                    routeTemplate: CoreAPIMethod.Configuration.ToString()
                    );
                // TODO: Create a configuration parameter deciding whether API-documentation should be available without authorization.
                // TODO: We could also change this between production and test, for instance tightening down access to 
                // TODO: API-documentation in test, while having anonymous access in production, hiding new features until launched.
                connector(method, true);
            }

            types.ForEach(t => {
                InvalidTypeException.AssertAssignable(t, typeof(BaseEntity), null);
                var a = t.GetClassAttribute();
                if (
                    !t.IsAbstract &&
                    !typeof(BaseEntity).Equals(t) &&
                    !typeof(Property).IsAssignableFrom(t) && // "Independent" properties would be a meaningless concept
                    a.AccessLevelWrite < AccessLevel.System) addEntityCreator(t);
                if (a.AccessLevelRead < AccessLevel.System || typeof(BaseEntity).Equals(t)) entityIndexCreator(t);
                if (a.AccessLevelRead < AccessLevel.System) historyCreator(t); // Must appear before addPropertyCreator
                if (a.AccessLevelWrite < AccessLevel.System) updatePropertyCreator(t);
                if (a.AccessLevelWrite < AccessLevel.System) propertyOperationCreator(t);
            });
        }

        /// <summary>
        /// Filters (ignores) if <see cref="APIMethodAttribute.Environment"/> does not match <see cref="ConfigurationAttribute.Environment"/>
        /// (but adds to <see cref="IgnoredMethods"/> first)
        /// 
        /// "Connect" this method to the database, giving it an id and fetching historical data
        /// 
        /// TODO: Find mechanism for setting invalid for methods no longer relevant (that is, old methods resisting in database
        /// TODO: no longer relevant since ConnectMethodWithDatabase is not called for them)
        /// </summary>
        /// <param name="method"></param>
        /// <param name="db"></param>
        private static void FilterConnectWithDatabaseAndAddMethod(APIMethod method, APIMethodOrigin origin, bool requiresAuthorization, IDatabase db) {
            if (method == null) throw new NullReferenceException(nameof(method));
            if (db == null) throw new NullReferenceException(nameof(db));

            if (method.A.Environment < Util.Configuration.A.Environment) {
                IgnoredMethods.Add(method);
                return;
            }
            var cid = GetOrAdd<ClassAndMethod>(typeof(APIMethod), System.Reflection.MethodBase.GetCurrentMethod().Name, db).Id;

            var identifier = new Func<string>(() => {
                switch (method.A.CoreMethod) {
                    case CoreAPIMethod.RootIndex:
                    case CoreAPIMethod.GenericMethod: return method.A.CoreMethod.ToString();
                    default: return method.RouteTemplates[0].Replace("/", "_").Replace("{", "_").Replace("}", "_");
                }
            })();
            InvalidIdentifierException.AssertValidIdentifier(identifier); // 
            GetOrAdd(typeof(APIMethod), identifier, db, enrichAndReturnThisObject: method);

            /// TODO: Duplicate code in <see cref="APIMethod.FilterConnectWithDatabaseAndAddMethod"/> and <see cref="Configuration.ConnectWithDatabase"/>
            void updater<T>(CoreP key, T value)
            { // Bug with auto formatting (CTRL-K, D)? Brace is not correct placed
                db.UpdateProperty(cid, method, key.A(), value, result: null);
            }

            if (method._entityType != null) updater(CoreP.EntityType, method._entityType);
            switch (method.A.CoreMethod) {
                case CoreAPIMethod.RootIndex: updater(CoreP.Name, "(" + method.A.CoreMethod + ")"); break;
                case CoreAPIMethod.GenericMethod: updater(CoreP.Name, method.RouteTemplates[0] + " (" + method.A.CoreMethod + ")"); break;
                default: updater(CoreP.Name, method.RouteTemplates[0]); break;
            }
            updater(CoreP.APIMethodOrigin, origin);
            updater(CoreP.RouteTemplate, method.RouteTemplates[0]);
            if (origin == APIMethodOrigin.Autogenerated) {
                updater(CoreP.Implementator, nameof(BaseController) + ".HandleCoreMethod" + method.A.CoreMethod);
            } else {
                updater(CoreP.Implementator, method.Controller.ToStringShort() + "." + method.ControllerMethod.Name);
            }
            updater(CoreP.RequiresAuthorization, requiresAuthorization);

            /// Construct sample URLs based on <see cref="PropertyKeyAttribute.SampleValues"/> for each parameter. 
            /// Permutate between all combinations
            /// TODO: Add check for <see cref="CoreP.Key"/> and only suggest <see cref="CoreP.Value"/>, 
            /// TODO: that are valid for the given key.
            var suggestedUrls = new List<string>();
            if (method.Parameters.Count == 0) {
                suggestedUrls.Add(method.RouteTemplates[0]);
            } else if (method.Parameters.All(p => p.Key.A.SampleValues != null && p.Key.A.SampleValues.Length > 0)) {
                /// We have sample values for all parameters. Permutate between them
                /// TODO: Make better code than this!
                var t = method.RouteTemplates[0];
                if (method.Parameters.Count <= 0) {
                    suggestedUrls.Add(t);
                } else {
                    var p = method.Parameters[0].Key;
                    p.A.SampleValues.ForEach(v0 => {
                        /// TODO: Make better code than this!
                        var t0 = t.Replace("{" + p.PToString + "}", v0);
                        if (method.Parameters.Count <= 1) {
                            suggestedUrls.Add(t0);
                        } else {
                            p = method.Parameters[1].Key;
                            p.A.SampleValues.ForEach(v1 => {
                                /// TODO: Make better code than this!
                                var t1 = t0.Replace("{" + p.PToString + "}", v1);
                                if (method.Parameters.Count <= 2) {
                                    suggestedUrls.Add(t1);
                                } else {
                                    p = method.Parameters[2].Key;
                                    p.A.SampleValues.ForEach(v2 => {
                                        /// TODO: Make better code than this!
                                        var t2 = t1.Replace("{" + p.PToString + "}", v2);
                                        if (method.Parameters.Count <= 3) {
                                            suggestedUrls.Add(t2);
                                        } else {
                                            // Add more permutations. 
                                            // TODO: Make better code than this!
                                            throw new NotImplementedException(nameof(method.Parameters) + ".Count >= 3");
                                        }
                                    });
                                }
                            });
                        }
                    });
                }
            }

            /// TODO: Add <see cref="PropertyOperation.SetInvalid"/> if already exists a <see cref="CoreP.SuggestedUrl"/>
            if (suggestedUrls.Count > 0) updater(CoreP.SuggestedUrl, string.Join("\r\n", suggestedUrls.Select(s => Util.Configuration.A.BaseUrl + s)));

            // Update all MethodAttribute properties
            /// TODO: Duplicate code in <see cref="APIMethod.FilterConnectWithDatabaseAndAddMethod"/> and <see cref="Configuration.ConnectWithDatabase"/>
            // TDOO: MOVE THIS TO A MORE GENERAL PLACE (Into BaseEntity for instance?
            //
            // TODO: BIG WEAKNESS HERE. We do not know the generic value of what we are asking for
            // TODO: The result will be to store as DBField.strv instead of a more precise type.
            // TODO: Implement some kind of copying of properties in order to avoid this!
            // TODO: (or rather, solve the general problem of using generics with properties)
            method.A.Properties.Values.ForEach(p => {
                if (typeof(bool).Equals(p.Key.Key.A.Type)) {
                    db.UpdateProperty(cid, method, p.Key, p.V<bool>(), result: null);
                    // TODO: Maybe replace this check with extension-method IsStoredAsStringInDatabase or similar...
                } else if (typeof(Type).Equals(p.Key.Key.A.Type) || p.Key.Key.A.Type.IsEnum || typeof(string).Equals(p.Key.Key.A.Type)) {
                    var value = p.V<string>();
                    if (method.A.CoreMethod != CoreAPIMethod.None) {
                        /// Add information about CoreMethod
                        /// TODO: This is very similar to <see cref="PropertyKeyAttribute.EnrichFrom"/> 
                        /// TODO: We should use some of the same mechanism there.
                        var coreA = method.A.CoreMethod.GetAgoRapideAttributeT();
                        if (p.Key.Key.CoreP.Equals(CoreP.Description) && !string.IsNullOrEmpty(coreA.A.Description)) { // TODO: Do this in a more streamlined manner!
                            if (string.IsNullOrEmpty(value)) {
                                value = coreA.A.Description;
                            } else {
                                value += (value.EndsWith(".") ? "" : ".") + "\r\nCore " + nameof(coreA.A.Description) + ": " + coreA.A.Description;
                            }
                        } else if (p.Key.Equals(CoreP.LongDescription) && !string.IsNullOrEmpty(coreA.A.LongDescription)) { // TODO: Do this in a more streamlined manner!
                            if (string.IsNullOrEmpty(value)) {
                                value = coreA.A.LongDescription;
                            } else {
                                value += (value.EndsWith(".") ? "" : ".") + "\r\nCore " + nameof(coreA.A.LongDescription) + ": " + coreA.A.LongDescription;
                            }
                        }
                    }
                    db.UpdateProperty(cid, method, p.Key, value, result: null);
                } else {
                    throw new InvalidTypeException(p.Key.Key.A.Type, "Not implemented copying of properties. Details: " + p.ToString());
                }

            });
            _allMethods.Add(method);
        }

        public override string ToHTMLTableRowHeading(Request request) => "<tr><th>" + nameof(Name) + "</th><th>" + nameof(CoreAPIMethod) + "</th><th>" + nameof(CoreP.EntityType) + "</th><th>" + nameof(CoreP.AccessLevelUse) + "</th><th>" + nameof(CoreP.Description) + "</th><th>" + nameof(Created) + "</th></tr>";

        public override string ToHTMLTableRow(Request request) => "<tr><td>" +
            (Id <= 0 ? Name.HTMLEncode() : request.CreateAPILink(this)) + "</td><td>" +
            PV(CoreP.CoreAPIMethod.A(), CoreAPIMethod.None).Use(c => c == CoreAPIMethod.None ? "&nbsp;" : c.ToString()) + "</td><td>" +
            (EntityType?.ToStringVeryShort() ?? "&nbsp;") + "</td><td>" +
            PV<AccessLevel>(CoreP.AccessLevelUse.A()) + "</td><td>" +
            PV(CoreP.Description.A(), "[NO DESCRIPTION AVAILABLE]").HTMLEncodeAndEnrich(request) + "</td><td>" +
            (RootProperty?.Created.ToString(DateTimeFormat.DateHourMin) ?? "&nbsp;") + "</td></tr>\r\n";

        public class MethodAttributeInitialisationException : ApplicationException {
            public MethodAttributeInitialisationException(string message) : base(message) { }
        }

        public class MethodNotFoundException : ApplicationException {
            public MethodNotFoundException(CoreAPIMethod coreMethod, Type entityType) : this(Util.BreakpointEnabler + nameof(coreMethod) + ": " + coreMethod + ", " + nameof(entityType) + ": " + entityType.ToStringShort()) { }
            public MethodNotFoundException(string message) : base(message) { }
        }

        public class InvalidControllernameException : ApplicationException {
            public InvalidControllernameException(string message) : base(message) { }
        }
    }
}
