using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AgoRapide.Core;
using AgoRapide.API;
using AgoRapide.Database;

namespace AgoRapide {

    /// <summary>
    /// TODO: Consider FORCING implementation of all these methods in the client application
    /// TODO: (or rather, create <see cref="APIMethodOrigin.Autogenerated"/>)
    /// 
    /// Note how we DO NOT set any <see cref="AgoRapideAttribute.Description"/> for <see cref="CoreProperty.CoreMethod"/> 
    /// but instead rely on the <see cref="AgoRapideAttribute.Description"/> set here. 
    /// This comment describes the recommended approach to setting attributes when the type given (<see cref="AgoRapideAttribute.Type"/>) 
    /// is one of your own classes / enums, or one of the AgoRapide classes / enums 
    /// </summary>
    [AgoRapide(Description = "Represents core AgoRapide API methods that must be available in the client application.")]
    public enum CoreMethod {
        None,

        /// <summary>
        /// TODO: LINK THIS SOMEWHERE
        /// </summary>
        [AgoRapide(Description = "\"Starting point\" for API. Will usually return HTML-format regardless of -" + nameof(ResponseFormat) + "- requested by client")]
        RootIndex,

        /// <summary>
        /// Describes methods like api/APIMethod/{id}, api/Person/{id} and so on. Also used for api/Property/{id}
        /// See <see cref="BaseController{TProperty}.HandleCoreMethodEntityIndex"/>
        /// </summary>
        [AgoRapide(Description = "Basic access to entities.")]
        EntityIndex,

        //[AgoRapide(Description = "Documentation about API methods")]
        //MethodIndex,

        //[AgoRapide(Description = "Basic access to properties")]
        //PropertyIndex,
            
        [AgoRapide(Description = "Adding of entities. Corresponding -" + nameof(APIMethodOrigin.Autogenerated) + "- -" +nameof(APIMethod<CoreProperty>) + "- will get parameters according to -" + nameof(Extensions.GetObligatoryChildProperties) + "-")]
        AddEntity,

        [AgoRapide(Description = 
            "Calls -" + nameof(IDatabase<CoreProperty>.UpdateProperty) + "-. " +
            "Will create a new property if it did not exist already or if the old values was different.\r\n" +
            "If property existed with same value then its -" + nameof(DBField.valid) + "- and -" + nameof(DBField.vid) + "- will be updated")]        
        UpdateProperty,

        [AgoRapide(Description = 
            "Calls -" + nameof(IDatabase<CoreProperty>.GetEntityHistory) + "- for the given property. " +
            "If the property is an entity root-property then all history information for that entity is returned.")]
        History,

        [AgoRapide(Description = 
            "Executes either -" + nameof(AgoRapide.PropertyOperation.SetValid) + "- or -" + nameof(AgoRapide.PropertyOperation.SetValid) + "-.")]
        PropertyOperation,

        [AgoRapide(Description = 
            "The application specific general query when looking up a context. " +
            "Typical example could be somebody in a support department looking up a customer based on whatever identification is available. " +
            "Result is communicated through -" + nameof(GeneralQueryResult<CoreProperty>) + "-")]
        GeneralQuery,

        /// <summary>
        /// See <see cref="BaseController{TProperty}.AgoRapideGenericMethod"/>
        /// </summary>
        [AgoRapide(Description =
            "Maps to the {*url} route, " +
            "in other words it is the method handling all API calls not recognized by the ASP .NET routing mechanism.\r\n" +
            "The implementation of this method calls -" + nameof(BaseController<CoreProperty>) + "." + nameof(BaseController<CoreProperty>.AgoRapideGenericMethod) + "- " +
            "(see that method again for further documentation).")]
        GenericMethod,

        /// <summary>
        /// See <see cref="BaseController{TProperty}.HandleCoreMethodExceptionDetails"/>
        /// </summary>
        [AgoRapide(Description = 
            "Offers details about the last exception that occurred.\r\n" +
            "The implementation of this method calls -" + nameof(BaseController<CoreProperty>) + "." + nameof(BaseController<CoreProperty>.HandleCoreMethodExceptionDetails) + "- " +
            "(see that method again for further documentation).")]            
        ExceptionDetails,

        ///// <summary>
        ///// TODO: Decide if necessary. Can an ordinary AddProperty be sufficient for this?
        ///// </summary>
        //[AgoRapide(Description = "The method activating use of -" + nameof(CoreProperty) + "." + nameof(CoreProperty.EntityToRepresent) + "- and " + nameof(CoreProperty) + "." + nameof(CoreProperty.RepresentedByEntity) + ".")]
        //Represent,

        //[AgoRapide(Description = "Lists all API-methods.")]
        //MethodAll,

        ///// <summary>
        ///// TODO: Decide if this is really needed
        ///// </summary>
        //HTTPStatus,
    }
}
