// Copyright (c) 2016, 2017 Bjørn Erling Fløtten, Trondheim, Norway
// MIT licensed. Details at https://github.com/AgoRapide/AgoRapide/blob/master/LICENSE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AgoRapide.Core;
using AgoRapide.API;
using AgoRapide.Database;

namespace AgoRapide {

    /// <summary>
    /// Note how we DO NOT set any <see cref="PropertyKeyAttribute.Description"/> for <see cref="CoreP.CoreAPIMethod"/> 
    /// but instead rely on the <see cref="ClassAttribute.Description"/> set here. 
    /// This comment describes the recommended approach to setting attributes when the type given (<see cref="PropertyKeyAttribute.Type"/>) 
    /// is one of your own classes / enums, or one of the AgoRapide classes / enums 
    /// </summary>
    [Enum(
        Description = "Represents core AgoRapide API methods that must be available in the client application.",
        AgoRapideEnumType = EnumType.EnumValue
    )]
    public enum CoreAPIMethod {
        None,

        /// <summary>
        /// TODO: LINK THIS SOMEWHERE
        /// </summary>
        [EnumValue(Description = "\"Starting point\" for API. Will usually return HTML-format regardless of -" + nameof(ResponseFormat) + "- requested by client")]
        RootIndex,

        [EnumValue(Description ="Access to -" + nameof(Configuration) + "-.")]
        Configuration,

        /// <summary>
        /// Describes methods like api/APIMethod/{id}, api/Person/{id} and so on. Also used for api/Property/{id}
        /// See <see cref="BaseController.HandleCoreMethodEntityIndex"/>
        /// </summary>
        [EnumValue(Description = "Basic access to entities.")]
        EntityIndex,

        [EnumValue(Description = "Adding of entities. Corresponding -" + nameof(APIMethodOrigin.Autogenerated) + "- -" +nameof(APIMethod) + "- will get parameters according to -" + nameof(Extensions.GetObligatoryChildProperties) + "-")]
        AddEntity,

        [EnumValue(Description = 
            "Calls -" + nameof(BaseDatabase.UpdateProperty) + "-. " +
            "Will create a new property if it did not exist already or if the old values was different.\r\n" +
            "If property existed with same value then its -" + nameof(DBField.valid) + "- and -" + nameof(DBField.vid) + "- will be updated")]        
        UpdateProperty,

        [EnumValue(Description = 
            "Calls -" + nameof(BaseDatabase.GetEntityHistory) + "- for the given property. " +
            "If the property is an entity root property (" + nameof(CoreP.RootProperty) + ") then all history information for that entity is returned.")]
        History,

        [EnumValue(Description = 
            "Executes either -" + nameof(AgoRapide.PropertyOperation.SetValid) + "- or -" + nameof(AgoRapide.PropertyOperation.SetValid) + "-.")]
        PropertyOperation,

        [EnumValue(Description = 
            "The application specific general query when looking up a context. " +
            "Typical example could be somebody in a support department looking up a customer based on whatever identification is available. " +
            "Result is communicated through -" + nameof(GeneralQueryResult) + "-")]
        GeneralQuery,

        /// <summary>
        /// See <see cref="BaseController.AgoRapideGenericMethod"/>
        /// </summary>
        [EnumValue(Description =
            "Maps to the {*url} route, " +
            "in other words it is the method handling all API calls not recognized by the ASP .NET routing mechanism.\r\n" +
            "The implementation of this method calls -" + nameof(BaseController) + "." + nameof(BaseController.AgoRapideGenericMethod) + "- " +
            "(see that method again for further documentation).")]
        GenericMethod,

        /// <summary>
        /// See <see cref="BaseController.HandleCoreMethodExceptionDetails"/>
        /// </summary>
        [EnumValue(Description = 
            "Offers details about the last exception that occurred.\r\n" +
            "The implementation of this method calls -" + nameof(BaseController) + "." + nameof(BaseController.HandleCoreMethodExceptionDetails) + "- " +
            "(see that method again for further documentation).")]            
        ExceptionDetails,
    }
}
